<template>
  <div id="sparc-record-detail">
    <div id="left-content-column">
      <div class="content-container__info__title" />
      <div class="content-container__info__text">
        The Sparc Dataportal is an easily accessible resource to find, visualize
        and access data generated by the NIH SPARC project.
      </div>
    </div>
    <div id="right-content-column">
      <div class="sparc-details" />
    </div>
  </div>
</template>

<script>
export default {
  name: 'SparcRecordDetail',
  components: {},

  props: {},

  data() {
    return {
      id: ''
    }
  },
  computed: {},
  watch: {
    $route() {
      this.id = this.$route.params.id
    }
  },
  mounted() {
    this.id = this.$route.params.id
  },
  methods: {}
}
</script>

<style lang="scss" scoped>
#sparc-record-detail {
  display: flex;
  flex-direction: row;
  width: 100%;
}
</style>
